[tool.poetry]
name = "exasol-data-science-utils-python"
version = "0.1.0"
description = "Exasol specific Data Science utilities for the Python programming language"

license = "MIT"

authors = [
    "Torsten Kilias <torsten.kilias@exasol.com>",
    "Anastasiia Sergienko <anastasiia.sergienko@exasol.com>"
]

readme = 'README.md'

repository = "https://github.com/exasol/data-science-utils-python"
homepage = "https://github.com/exasol/data-science-utils-python"

keywords = ['exasol', 'data-science']

[tool.poetry.dependencies]
python = ">=3.6.1"
pyexasol = "^0.17.0"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
pytest-cov = "^2.10.1"
