name: Build Language Container

on: [ push ]

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: 1.2.2
      - name: uninstall
        run: pip uninstall -y urllib3 chardet
      - name: install requests
        run: pip3 install --upgrade requests
      - name: Build language container
        run: ./build_language_container.sh
